project:
  type: manuscript

manuscript:
  article: paper-imaginaries-hype-myth.qmd

notebook-links: true

format:
  html:
    comments:
      hypothesis: true
  docx: default
  # jats: default

  #(other formats)
  pdf: default

execute:
  freeze: true



